ALTER TABLE "persons"
  ADD COLUMN IF NOT EXISTS "etnia" VARCHAR(80);

ALTER TABLE "profili_salute_persone"
  ADD COLUMN IF NOT EXISTS "peso" DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS "altezza" DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS "bmi" DECIMAL(4,1);
