version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: em-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./letsencrypt-webroot:/var/www/certbot
      - ./ssl:/etc/letsencrypt
      - ./logs/nginx:/var/log/nginx
    environment:
      - TZ=Europe/Rome
    depends_on: []

  # One-shot certificate request container (run manually when DNS points to server)
  certbot:
    image: certbot/certbot:latest
    container_name: em-certbot
    volumes:
      - ./letsencrypt-webroot:/var/www/certbot
      - ./ssl:/etc/letsencrypt
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "trap exit TERM; while :; do sleep 3600; done"

  # Cron-like renew container (optional: can be disabled until cert issued)
  certbot-renew:
    image: certbot/certbot:latest
    container_name: em-certbot-renew
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while :; do certbot renew --webroot -w /var/www/certbot --non-interactive --quiet && nginx -s reload || true; sleep 12h; done"
    volumes:
      - ./letsencrypt-webroot:/var/www/certbot
      - ./ssl:/etc/letsencrypt
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nginx

networks:
  default:
    name: em-net
    driver: bridge