# Alertmanager Configuration for Document Management System
# Handles alert routing, grouping, and notifications

global:
  # SMTP configuration for email notifications
  smtp_smarthost: 'smtp.yourmailprovider.com:587'
  smtp_from: 'alerts@yourdomain.com'
  smtp_auth_username: 'alerts@yourdomain.com'
  smtp_auth_password: 'your-smtp-password'
  smtp_require_tls: true
  
  # Slack configuration
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
  
  # Default notification settings
  resolve_timeout: 5m
  http_config:
    follow_redirects: true

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  # Default settings for all alerts
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  # Specific routing rules
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 15m
      routes:
        # Database issues - notify DBA team immediately
        - match:
            team: database
          receiver: 'database-team'
          group_wait: 0s
          repeat_interval: 5m
        
        # Security issues - notify security team immediately
        - match:
            team: security
          receiver: 'security-team'
          group_wait: 0s
          repeat_interval: 5m
        
        # Platform issues - notify platform team
        - match:
            team: platform
          receiver: 'platform-team'
          group_wait: 0s
          repeat_interval: 10m
    
    # Warning alerts - standard notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
      routes:
        # Deployment issues
        - match:
            team: deployment
          receiver: 'deployment-team'
          repeat_interval: 30m
        
        # Backend issues
        - match:
            team: backend
          receiver: 'backend-team'
          repeat_interval: 1h
    
    # Info alerts - low priority
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      group_interval: 10m
      repeat_interval: 12h
    
    # Business alerts
    - match:
        team: product
      receiver: 'product-team'
      group_wait: 10m
      repeat_interval: 4h
    
    # Maintenance window - suppress alerts
    - match:
        maintenance: 'true'
      receiver: 'null-receiver'
    
    # Test alerts - development only
    - match:
        environment: 'test'
      receiver: 'test-alerts'
      repeat_interval: 24h

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  
  # Suppress individual service alerts when the entire cluster is down
  - source_match:
      alertname: 'ServiceDown'
      service: 'cluster'
    target_match_re:
      alertname: 'ServiceDown'
    equal: ['cluster']
  
  # Suppress high response time alerts when service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighAPIResponseTime'
    equal: ['instance']
  
  # Suppress memory alerts when disk is full (likely related)
  - source_match:
      alertname: 'DiskSpaceLow'
    target_match:
      alertname: 'HighMemoryUsage'
    equal: ['instance']

# Receiver configurations
receivers:
  # Default receiver - basic email notification
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@yourdomain.com'
        subject: '[ALERT] {{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
        headers:
          Priority: 'normal'
  
  # Critical alerts - multiple notification channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@yourdomain.com,oncall@yourdomain.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} - IMMEDIATE ACTION REQUIRED'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Team: {{ .Labels.team }}
          Instance: {{ .Labels.instance }}
          Runbook: {{ .Annotations.runbook_url }}
          
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .EndsAt }}Ended: {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
          {{ end }}
        headers:
          Priority: 'high'
    
    slack_configs:
      - api_url: '{{ .SlackAPIURL }}'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          
          *Labels:* {{ range .Labels.SortedPairs }}`{{ .Name }}={{ .Value }}` {{ end }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        color: 'danger'
        send_resolved: true
    
    pagerduty_configs:
      - routing_key: 'your-pagerduty-integration-key'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.instance }}'
        severity: 'critical'
        details:
          summary: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
          description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
          runbook_url: '{{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}'
  
  # Database team notifications
  - name: 'database-team'
    email_configs:
      - to: 'dba@yourdomain.com,devops@yourdomain.com'
        subject: '[DB ALERT] {{ .GroupLabels.alertname }}'
        body: |
          Database Alert Detected
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.database }}
          Instance: {{ .Labels.instance }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    
    slack_configs:
      - channel: '#database-alerts'
        title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          
          *Database:* {{ .Labels.database }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        color: 'warning'
  
  # Security team notifications
  - name: 'security-team'
    email_configs:
      - to: 'security@yourdomain.com,devops@yourdomain.com'
        subject: '[SECURITY ALERT] {{ .GroupLabels.alertname }}'
        body: |
          🔒 Security Alert Detected
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Source IP: {{ .Labels.source_ip }}
          Instance: {{ .Labels.instance }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
        headers:
          Priority: 'high'
    
    slack_configs:
      - channel: '#security-alerts'
        title: '🔒 Security Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          
          *Source IP:* {{ .Labels.source_ip }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        color: 'danger'
  
  # Platform team notifications
  - name: 'platform-team'
    email_configs:
      - to: 'platform@yourdomain.com,devops@yourdomain.com'
        subject: '[PLATFORM] {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - channel: '#platform-alerts'
        title: '⚙️ Platform Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'
  
  # Deployment team notifications
  - name: 'deployment-team'
    slack_configs:
      - channel: '#deployment-alerts'
        title: '🚀 Deployment Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          
          *Environment:* {{ .Labels.environment }}
          *Deployment ID:* {{ .Labels.deployment_id }}
          {{ end }}
        color: 'warning'
  
  # Backend team notifications
  - name: 'backend-team'
    email_configs:
      - to: 'backend@yourdomain.com'
        subject: '[BACKEND] {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - channel: '#backend-alerts'
        title: '⚡ Backend Alert: {{ .GroupLabels.alertname }}'
        color: 'warning'
  
  # Product team notifications
  - name: 'product-team'
    email_configs:
      - to: 'product@yourdomain.com'
        subject: '[BUSINESS METRICS] {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - channel: '#product-metrics'
        title: '📊 Business Metrics Alert: {{ .GroupLabels.alertname }}'
        color: 'good'
  
  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@yourdomain.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        color: 'warning'
  
  # Info alerts
  - name: 'info-alerts'
    slack_configs:
      - channel: '#alerts-info'
        title: 'ℹ️ Info: {{ .GroupLabels.alertname }}'
        color: 'good'
  
  # Test alerts
  - name: 'test-alerts'
    email_configs:
      - to: 'test@yourdomain.com'
        subject: '[TEST] {{ .GroupLabels.alertname }}'
  
  # Null receiver for suppressed alerts
  - name: 'null-receiver'

# Time intervals for maintenance windows
time_intervals:
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        months: ['1:12']
        days_of_month: ['1:31']
  
  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '17:00'
        weekdays: ['monday:friday']
        location: 'UTC'
  
  - name: 'weekend'
    time_intervals:
      - weekdays: ['saturday', 'sunday']